#!/bin/sh
#		
#		webfinger.sh - webfinger from the shell
#		
#		dependencies: sh, sed, xargs, curl, awk
#       
#		Copyright 2012 Florian Hülsmann <fh@cbix.de>
#       
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 3 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.
#

export WEBFINGERID=`echo -n acct:$1 | sed 's/:/%3a/g' | sed 's/@/%40/g'`
HOSTMETA="`echo $1 | sed 's/^\(.*\)@\(.*\)/http:\/\/\2\/\.well-known\/host-meta/'`"
HOSTMETASSL="`echo "$HOSTMETA" | sed 's/^http/https/'`"
(curl -s -L "$HOSTMETASSL" 2>/dev/null || curl -s -L "$HOSTMETA" 2>/dev/null) \
	| awk '
	BEGIN {
		RS = "<";
		FS = ">";
	}
	tolower($1) ~ /^link.+rel[ \t\f\n\r\v]*=[ \t\f\n\r\v]*(\"lrdd\"|\'"'"'lrdd\'"'"'|lrdd)/ {
		template = $1;
		match(template, /template[ \t\f\n\r\v]*=[ \t\f\n\r\v]*((\".*\"|\'"'"'.*\'"'"'))/);
		if(RLENGTH < 0) exit 1;
		template = substr(template, RSTART, RLENGTH);
		sub(/^template[ \t\f\n\r\v]*=[ \t\f\n\r\v]*[\'"'"'\"]/, "", template);
		sub(/[\'"'"'\"]$/, "", template);
		gsub(/\{uri\}/, ENVIRON["WEBFINGERID"], template);
		print "'"'"'" template "'"'"'";
		exit 0;
	}' \
	| xargs curl -s -L || echo "Could not webfinger $1" 1>&2
